version: '3.8'
services:
  
  buy-and-sell:
    build: ./buy-and-sell
    container_name: bs_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true