version: '3.8'
services:
  BACK:
    build: ./BACK
    container_name: back_backend
    ports:
      - '4000:4000'
    volumes:
      - ./back:/app
      - ./app/node_modules

  
  buy-and-sell:
    build: ./buy-and-sell
    container_name: bs_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true