runtime: nodejs
env: flex
manual_scaling:
  instances: 1 
beta_settings:
  cloud_sql_instances: buy-and-sell-387512:us-central1:buy-and-sell-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: '@Stacy2009'
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-sell-387512:us-central1:buy-and-sell-db